---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-storage
  namespace: hamann
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-ceph-hdd-ms1"
